import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Sign page",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <main className="flex min-h-screen items-center justify-center">
      {children}
    </main>
  );
};

export default Layout;
